### ISSUE TITLE
A new paper on Unified MM understanding and generation

### ISSUE THREAD

**Issue by thudzj** [ChaofanTao/Autoregressive-Models-in-Vision-Survey#6]
Hi Chaofan,

Congratulations on the amazing repository! We are excited to share our latest work in unified multimodal understanding and generation [Orthus: Autoregressive Interleaved Image-Text Generation with Modality-Specific Heads](https://arxiv.org/pdf/2412.00127). It would be fantastic if you could place it within the appropriate category to enhance its visibility. 

Best,
Zhijie Deng

**Comment by inFaaa** [comment]
Thanks for your suggestion. We have added your paper to our repo! ❤️
